services:

  reminder_api:
    container_name: reminder_api
    build:
      context: .
      dockerfile: ./dockerfiles/Dockerfile.api
    env_file: .env
    ports:
      - 8080:80
    restart: unless-stopped
    depends_on:
      - reminder_db

  reminder_db:
    image: mongo:5.0.9
    ports:
      - 27017:27017
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example      
