FROM python:3.10.5-slim

RUN adduser reminder_srv

WORKDIR /home/reminder_srv

COPY --chown=reminder_srv:reminder_srv ../requirements.txt requirements.txt
COPY --chown=reminder_srv:reminder_srv ../app.py app.py
RUN pip install --upgrade pip
RUN pip install -r requirements.txt
RUN pip install gunicorn

COPY --chown=reminder_srv:reminder_srv ../reminder reminder
COPY --chown=reminder_srv:reminder_srv ../boot_api.sh ./
RUN chmod +x boot_api.sh

USER reminder_srv

ENTRYPOINT ["./boot_api.sh"]

