FROM python:3.10.5-slim

RUN adduser user_srv

WORKDIR /home/user_srv

COPY ../requirements.txt requirements.txt
COPY ../app.py app.py
RUN pip install --upgrade pip
RUN pip install -r requirements.txt
RUN pip install gunicorn

COPY ../user user
COPY ../boot_api.sh ./
RUN chmod +x boot_api.sh

RUN chown -R user_srv:user_srv ./
USER user_srv

ENTRYPOINT ["./boot_api.sh"]

