FROM python:3.10.5-slim

RUN adduser user_srv

WORKDIR /home/user_srv

COPY --chown=user_srv:user_srv ../requirements.txt requirements.txt
COPY --chown=user_srv:user_srv ../app.py app.py
RUN pip install --upgrade pip
RUN pip install -r requirements.txt
RUN pip install gunicorn

COPY --chown=user_srv:user_srv ../user user
COPY --chown=user_srv:user_srv ../boot_api.sh ./
RUN chmod +x boot_api.sh

USER user_srv

ENTRYPOINT ["./boot_api.sh"]
